name: MamanghoSystem
main: me.ministrie.main.MamanghoSystem
author: Ministrie
authors: [최태성, Ministrie]
version: 1.0.0
depend: [ProtocolLib, LuckPerms, ImageFrame]
softdepend: []
api-version: 1.21
load: STARTUP

commands:
  system:
    description: system command
  namechange:
    description: namechange command
    aliases: [닉네임변경]
  sharelocation:
    description: share location command
    aliases: [위치공유]
  help:
    description: help command
    aliases: [도움말]
  image:
    description: image map management command
    aliases: [이미지, dlalwl, DLALWL]
  tell:
    description: player to player messsage command
    aliases: [w, msg]